spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petMemory?serverTimezone=UTC&characterEncoding=UTF-8
    username: jin
    password: jj1552918
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages, errors

  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug